server {
    listen 80;
    listen [::]:80;
    server_name url.baule.fr;

    # Redirige HTTP → HTTPS (décommente si tu as un certificat SSL)
    # return 301 https://$host$request_uri;

    root /var/www/flashlink;
    index index.php;

    # Bloque l'accès direct au JSON
    location = /urls.json {
        deny all;
        return 404;
    }

    location = /create.php {
        include fastcgi_params;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;  # adapte la version PHP
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location / {
        try_files $uri $uri/ /index.php?id=$uri;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;  # adapte la version PHP
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
